Add edit features
tiendat97/redux pull request #5
Opened 2018-08-03 10:56 UTC by tiendat97

2018-08-03 15:30 UTC, ghost requested changes

2018-08-03 15:30 UTC, dungla4 commented on src/actions/index.js
> +export const editTodo = id => ({
Tại sao mình cần editTodo action?

2018-08-03 15:30 UTC, dungla4 commented on src/components/Todo.js
> +import { connect } from "react-redux";
Em xem thêm khái niệm về Component và Container. Component sẽ chỉ làm việc với props/state của nó, còn containers mới là thành phần liên kết với store
Sau khi tìm hiểu về Container và Component rồi thì em xác định xem trong app todo này thì thành phần nào sẽ là Container, thành phần nào sẽ là Component

2018-08-04 12:58 UTC, tiendat97 commented on src/actions/index.js
> +export const editTodo = id => ({
editTodo action có tác dụng đổi giá trị logic của isEditing sau mỗi lần CLick Edit, Save hay Cancel ạ

2018-08-04 12:59 UTC, tiendat97 commented on src/components/Todo.js
> +import { connect } from "react-redux";
em hiểu ý anh, em sẽ sắp xếp lại ạ

2018-08-04 13:03 UTC, merged